version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  zookeeper:
    image: arm64v8/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: obsidiandynamics/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /tmp/kafka-logs
    depends_on:
      - zookeeper

  flask_agent:
    build: ./flask_agent
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - mosquitto
    volumes:
      - ./flask_agent:/app
